sudo: required
services:
  - docker

before_install:
  - docker build -t mazzama/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run mazzama/react-test npm test -- --coverage

after_success:
  - docker build -t mazzama/practice-docker-client ./client
  - docker build -t mazzama/practice-docker-nginx ./nginx
  - docker build -t mazzama/practice-docker-server ./server
  - docker build -t mazzama/practice-docker-worker ./worker
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push mazzama/practice-docker-client
  - docker push mazzama/practice-docker-nginx
  - docker push mazzama/practice-docker-server
  - docker push mazzama/practice-docker-worker